# steps:
#  - name: 'gcr.io/cloud-builders/docker'
#     entrypoint: 'gcloud'
#     args: ['-c', 'mv', 'document.txt', 'gs://desu-project/GCP-trigger-files/']

steps:
- name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'gs://mybucket/results.zip', 'previous_results.zip']
# operations that use previous_results.zip and produce new_results.zip
- name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'new_results.zip', 'gs://mybucket/results.zip']

