# steps:
#  - name: 'gcr.io/cloud-builders/docker'
#     entrypoint: 'gcloud'
#     args: ['-c', 'mv', 'document.txt', 'gs://desu-project/GCP-trigger-files/']


 #gcloud beta builds triggers export GCP-trigger-new --destination=cloudbuild.yaml
# - name: gcr.io/cloud-builders/gsutil
#   args: ['cp', 'document.txt',]
# # operations that use previous_results.zip and produce new_results.zip
# - name: gcr.io/cloud-builders/gsutil
#   args: ['cp', 'gs://desu-project/GCP-trigger-files/']

# steps:
# - name: 'ubuntu'
#   args: ['echo', 'hello world']


steps:
 - name: 'gcr.io/cloud-builders/gcloud'
   args: ['cp', 'gsutil cp https://github.com/Cloud-Build-Trigger-Bucket/document.txt', 'gs://desu-project/desu-project/GCP-trigger-files']
   #args: ['cp', 'gs://Generalproject/index.html', 'gs://svproject/cloudbuild_data/index.html']
   #gsutil cp [OPTION]... src_url dst_url

- name: 'gcr.io/cloud-builders/go'
  args: ['install', '.']
logsBucket: 'gs://${PROJECT_ID}_bucket'
