# steps:
#  - name: 'gcr.io/cloud-builders/docker'
#     entrypoint: 'gcloud'
#     args: ['-c', 'mv', 'document.txt', 'gs://desu-project/GCP-trigger-files/']


 #gcloud beta builds triggers export GCP-trigger-new --destination=cloudbuild.yaml
# - name: gcr.io/cloud-builders/gsutil
#   args: ['cp', 'document.txt',]
# # operations that use previous_results.zip and produce new_results.zip
# - name: gcr.io/cloud-builders/gsutil
#   args: ['cp', 'gs://desu-project/GCP-trigger-files/']

# steps:
# - name: 'ubuntu'
#   args: ['echo', 'hello world']

steps:
- name: 'gcr.io/cloud-builders/gsutil'
  entrypoint: 'bash'
#   args: ['echo', 'Hello world!']
  args: ['-m', 'cp', '-r', '/Cloud-Build-Trigger-Bucket', 'gs://desu-project/GCP-trigger-files/']
logsBucket: 'gs://desu-project/GCP-trigger-files/'
serviceAccount: 'projects/panel-379806/serviceAccounts/58358689186@cloudbuild.gserviceaccount.com'
options:
  logging: GCS_ONLY


# # Copy the .jar to our volume
# cp /document.txt gs://desu-project/GCP-trigger-files/



