# steps:
#  - name: 'gcr.io/cloud-builders/docker'
#     entrypoint: 'gcloud'
#     args: ['-c', 'mv', 'document.txt', 'gs://desu-project/GCP-trigger-files/']

steps:
 gcloud beta builds triggers export GCP-trigger-new --destination=cloudbuild.yaml
# - name: gcr.io/cloud-builders/gsutil
#   args: ['cp', 'document.txt',]
# # operations that use previous_results.zip and produce new_results.zip
# - name: gcr.io/cloud-builders/gsutil
#   args: ['cp', 'gs://desu-project/GCP-trigger-files/']

- name: gcr.io/cloud-builders/gcloud
    id: Trigger application image build
    args:
      - beta
      - builds
      - triggers
      - run
      - GCP-trigger-new
      - --branch=main

